"""
run_pipeline.py
---------------
End-to-end orchestrator for the Sierra Leone rice-yield pipeline.

    data_prep  ->  features  ->  walk-forward evaluation  ->  figures  ->  report

Run from the repo root:   python -m src.run_pipeline

Saves to outputs/:
  results_table.csv, walk_forward_predictions.csv, model_report.md,
  figures/actual_vs_predicted.png, figures/feature_importance.png,
  figures/shap_summary.png

Author: Ibrahim Denis Fofanah — Pace University | RiseAfrica Foundation
"""

import os

from . import config
from . import data_prep
from . import features as F
from . import evaluation as E
from . import modeling
from . import visualize as V


def _verdict(results_df) -> str:
    """Honest one-paragraph verdict: did any ML model beat persistence?"""
    persistence_rmse = float(
        results_df.loc[results_df['Model'] == 'Baseline: persistence (t-1)', 'RMSE'].iloc[0])
    ml = results_df[~results_df['Model'].str.startswith('Baseline')]
    best = ml.sort_values('RMSE').iloc[0]
    overall_best = results_df.sort_values('RMSE').iloc[0]

    beat = best['RMSE'] < persistence_rmse
    lines = []
    if beat:
        lines.append(
            f"The best ML model ({best['Model']}, RMSE {best['RMSE']:.1f} kg/ha) "
            f"edges out the persistence baseline (RMSE {persistence_rmse:.1f} kg/ha) "
            f"by {persistence_rmse - best['RMSE']:.1f} kg/ha on the 7 held-out years.")
    else:
        lines.append(
            f"**No ML model beats the persistence baseline.** The best ML model "
            f"({best['Model']}) records RMSE {best['RMSE']:.1f} kg/ha versus "
            f"{persistence_rmse:.1f} kg/ha for simply predicting last year's yield. "
            f"On a 25-year national series this is the expected, honest outcome: with "
            f"~13–18 training rows there is not enough signal for a tree ensemble to "
            f"out-predict the strong autocorrelation that 'last year' already captures.")
    lines.append(
        f"Overall lowest RMSE across all five contenders: **{overall_best['Model']}** "
        f"(RMSE {overall_best['RMSE']:.1f}, R² {overall_best['R2']:.3f}, "
        f"MAE {overall_best['MAE']:.1f}).")
    lines.append(
        "Per the design rules, models were **not** tuned and features were **not** "
        "added to chase a higher R². R² across only 7 points is high-variance and can "
        "be negative; RMSE/MAE in kg/ha are the more interpretable metrics here.")
    return ' '.join(lines)


def write_report(results_df, feat, best_name) -> str:
    feature_cols = F.get_feature_cols(feat)
    table_md = results_df.to_markdown(index=False, floatfmt=('', '.3f', '.1f', '.1f'))

    md = f"""# Model Report — Rice Yield Prediction (Sierra Leone)

*Target:* **{config.TARGET}** (kg/ha) · *Source:* FAOSTAT 2000–2024 ·
*Generated by* `src/run_pipeline.py`

## 1. Design

- **Data.** FAOSTAT long-format CSV pivoted to one row per year, columns =
  crop × element. Only the **nine complete crops** (Rice, Cassava, Maize,
  Groundnuts, Oil palm fruit, Sweet potatoes, Sorghum, Cocoa beans, Plantains)
  and three elements (Production, Area harvested, Yield) are used. Yams,
  aggregates (`… primary`, `… n.e.c.`) and processed products are excluded.
- **Predictors ({len(feature_cols)}).** lag-1 of every crop × element column;
  rice-yield lags 1–3; past-only 3- and 5-year rolling means of rice yield;
  linear year trend; Ebola (2014–16), COVID (2020–21) and Feed Salone (2023+)
  dummies.
- **Validation.** Expanding-window walk-forward only — train on all years before
  the test year, predict that one year, for {config.TEST_YEARS[0]}–{config.TEST_YEARS[-1]}
  ({len(config.TEST_YEARS)} out-of-sample predictions). No random splits.
- **Models.** XGBoost (depth 2), GradientBoosting (depth 2), RandomForest
  (depth 3) — all shallow/regularized, fixed settings, no grid search — plus two
  baselines: persistence (last year's yield) and the 3-year rolling mean.

## 2. Anti-leakage rules applied

1. **No same-year features.** Every predictor for year *t* is knowable before
   *t* begins. Cross-crop signals enter only as their *t-1* value.
2. **Rolling means use past years only** — `shift(1)` is applied *before*
   `rolling()`, so year *t*'s window never includes year *t*.
3. **No rice production-per-hectare feature** — that reconstructs the target.
4. A runtime assertion in `features.py` fails the build if any bare same-year
   crop column appears among the predictors.

## 3. Results (walk-forward, {config.TEST_YEARS[0]}–{config.TEST_YEARS[-1]})

{table_md}

*Metrics computed across the {len(config.TEST_YEARS)} held-out yearly predictions.*

## 4. Verdict

{_verdict(results_df)}

## 5. Explainability

Feature importance and SHAP summary plots (`outputs/figures/`) are produced for
the best ML model (**{best_name}**), refit on the full leakage-free dataset
({feat.index.min()}–{feat.index.max()}) *after* evaluation — for interpretation
only, never for model selection.
"""
    path = os.path.join(config.OUT_DIR, 'model_report.md')
    os.makedirs(config.OUT_DIR, exist_ok=True)
    with open(path, 'w') as fh:
        fh.write(md)
    print(f'[report] saved {path}')
    return path


def main():
    os.makedirs(config.OUT_DIR, exist_ok=True)
    os.makedirs(config.FIG_DIR, exist_ok=True)

    # 1–2. Data prep + features
    wide = data_prep.load_and_pivot()
    data_prep.save_wide(wide)
    feat = F.build_features(wide)
    F.save_features(feat)
    feature_cols = F.get_feature_cols(feat)

    # 3. Walk-forward evaluation
    results_df, preds_df = E.walk_forward(feat)
    results_df.to_csv(os.path.join(config.OUT_DIR, 'results_table.csv'), index=False)
    preds_df.to_csv(os.path.join(config.OUT_DIR, 'walk_forward_predictions.csv'))

    # 4. Figures
    V.plot_actual_vs_pred(preds_df)

    best_name = E.best_ml_model_name(results_df)
    best_model = modeling.build_models()[best_name]
    X_full = feat[feature_cols].to_numpy()
    y_full = feat[config.TARGET].to_numpy()
    best_model.fit(X_full, y_full)         # refit on full data — interpretation only
    V.plot_feature_importance(best_model, feature_cols, best_name)
    try:
        V.plot_shap_summary(best_model, X_full, feature_cols, best_name)
    except Exception as exc:                # SHAP is optional / can be brittle
        print(f'[viz] SHAP summary skipped: {exc}')

    # 5. Report
    write_report(results_df, feat, best_name)

    print('\n================ FINAL RESULTS TABLE ================')
    print(results_df.to_string(index=False,
          formatters={'R2': '{:.3f}'.format,
                      'RMSE': '{:.1f}'.format,
                      'MAE': '{:.1f}'.format}))
    print('=====================================================')
    print(f"Best ML model: {best_name}")
    return results_df, preds_df


if __name__ == '__main__':
    main()
